services:
  db:
    image: postgres
    container_name: starsoft-db
    volumes:
      - ./scripts-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=starsoftpatrick
      - POSTGRES_DB=starsoft
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U patrick -d starsoft']
      interval: 1s
      timeout: 10s
      retries: 10
    ports: ['5432:5432']

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./src/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: patrick
      RABBITMQ_DEFAULT_PASS: starsoftpatrick
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_running']
      interval: 5s
      timeout: 10s
      retries: 10

  node:
    container_name: 'starsoft-challenge'
    hostname: 'host-starsoft-challenge'
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    volumes: [.:/home/node/app]
    ports: ['3000:3000']
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
